### PR TITLE
Switch to unobstrusive javascript

### PR DESCRIPTION
**Pull request by jason-fox**
- remove onsubmit()
-  add closure
- key. off class name like standard bootstrap.

### CODE REVIEW

**Review by infotexture — COMMENTED** [review]
This is so _unobtrusive_ that I don't get search results at all. 😅  

Built the sample docs from the dita-bootstrap plug-in using this branch, but the search box doesn't seem to respond to input. (If I enter "icons" for example, and hit <kbd>Enter</kbd>, nothing happens.)

May be user error, but I'm testing with the `develop` branch of the dita-bootstrap repo, and running the following command:

```console
dita --input=sample/document.ditamap \
--format=html5-bootstrap \
--args.hdr=/path/to/dita-bootstrap.lunr/includes/bs-navbar-lunr.hdr.xml \
--nav-toc=collapsible \
--output=out/sample-document-lunr-search
```

**Comment by jason-fox** [comment]
Weird - which DITA-OT  version are you using?

 
Screenshot 2023-09-17 at 21 29 35

**Comment by jason-fox** [comment]
I've tested with DITA-OT 4.0 and DITA-OT-4.1.1

**Comment by jason-fox** [comment]
Possible trouble shooting:

1 - re-run `dita install` in case the hook didn't file
2. try running **online mode* and run a webserver to view the result
3. try adding `--offline.mode=yes` and view without a webserver.

**Comment by jason-fox** [comment]
Here is an automated build with unobtrusive built off a branch - https://github.com/jason-fox/dita-bootstrap/actions/runs/6244578696

Result: https://jason-fox.github.io/dita-bootstrap/  - everything is working fine for me.

**Comment by infotexture** [comment]
> which DITA-OT version are you using?

I typically test with the tip of the dita-ot `develop` branch (so 4.1.1+ in this case).

Thanks for confirming. I'll continue troubleshooting assuming it's something peculiar to my setup. 

Since it worked before, I thought the difference might be related to the changes in this PR, but that appears to be a red herring. Perhaps something else has changed on my side.

**Comment by infotexture** [comment]
Turns out it was user error. 🤦 

✅ Verified in both online and offline modes. 

_Merging…_

**Pull request merged**
